development:
  adapter: postgresql
  encoding: unicode
  database: sample_shopapp_pg_development
  pool: 5
  username: maciek
  password: "maciek"
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sample_shopapp_mysql_test
  pool: 5
  username: maciek
  password: "maciek"
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sample_shopapp_mysql_production
  pool: 5
  username: maciek
  password: "maciek"
  host: localhost